[package]
name = "bevy_atmosphere"
description = "A procedural sky plugin for bevy"
version = "0.1.3"
edition = "2018"
authors = ["JonahPlusPlus <33059163+JonahPlusPlus@users.noreply.github.com>"]
license = "MIT"
documentation = "https://docs.rs/bevy_atmosphere"
homepage = "https://github.com/JonahPlusPlus/bevy_atmosphere"
repository = "https://github.com/JonahPlusPlus/bevy_atmosphere"

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render"] }

[dev-dependencies]
bevy = { version = "0.5" }
bevy_flycam = "0.5"

[[example]]
name = "cycle"
path = "examples/cycle.rs"
