[package]
name = "bevy_atmosphere"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = { version = "0.5", features = ["dynamic"]}

[dev-dependencies]
bevy_flycam = "*"

[[example]]
name = "cycle"
path = "examples/cycle.rs"